[package]
name = "zk_evm_abstractions"
version = "0.140.0"
edition = "2021"
authors = ["The Matter Labs Team <hello@matterlabs.dev>"]
homepage = "https://zksync.io/"
repository = "https://github.com/matter-labs/era-zk_evm_abstractions"
license = "MIT OR Apache-2.0"
keywords = ["blockchain", "zksync"]
categories = ["cryptography"]
description = "ZKsync EraVM abstractions"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
serde = { version = "1", features = ["derive"] }
static_assertions = "1"
num_enum = "0.6"

zkevm_opcode_defs = "=0.132.0"

[dev-dependencies]
hex = "0.4"
